# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: aayusharma1410
service: ai-cloud-operations-center

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: dev

  environment:
    INCIDENT_TABLE: IncidentTable

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"

functions:

  createIncident:
    handler: src/createIncident.handler
    events:
      - httpApi:
          path: /incident
          method: post

  getIncidents:
    handler: src/getIncidents.handler
    events:
      - httpApi:
          path: /incidents
          method: get

  dashboardStats:
    handler: src/dashboardStats.handler
    events:
      - httpApi:
          path: /dashboard
          method: get

  analyzeIncident:
    handler: src/analyzeIncident.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - IncidentTable
              - StreamArn

resources:
  Resources:
    IncidentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: IncidentTable
        BillingMode: PAY_PER_REQUEST

        StreamSpecification:
          StreamViewType: NEW_IMAGE

        AttributeDefinitions:
          - AttributeName: incidentId
            AttributeType: S

        KeySchema:
          - AttributeName: incidentId
            KeyType: HASH
